// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylqpdpckkqwucznpcebi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlscXBkcGNra3F3dWN6bnBjZWJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzODYwMjcsImV4cCI6MjA3Nzk2MjAyN30.B1MXuzAti69hrPH9-S-CCmEFfpO_FiRJ2-wadkt76j0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});